Testing `test/e2e/alcotest/failing/exception_in_test.ml'.
This run has ID `<uuid>'.

  [OK]          test-a          0   Passing.
> [FAIL]        test-a          1   Failing.
  [OK]          test-b          0   Another pass.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        test-a          1   Failing.                                   │
└──────────────────────────────────────────────────────────────────────────────┘
[exception] Dune__exe__Exception_in_test.Foo("message")

Logs saved to `<build-context>/_build/_tests/<test-dir>/test-a.001.output'.
 ──────────────────────────────────────────────────────────────────────────────

Full test results in `<build-context>/_build/_tests/<test-dir>'.
1 failure! in <test-duration>s. 3 tests run.
